-- ═══════════════════════════════════════════════════════════════════════════════
-- CAMLY SaaS — Estructura Completa de Base de Datos (DDL Limpio sin datos demo)
-- ═══════════════════════════════════════════════════════════════════════════════
-- Ejecución: Supabase Dashboard → SQL Editor → New Query → Pegar y ejecutar (Run)
--
-- Crea y configura desde cero las 6 tablas esenciales del sistema:
--   1. negocios
--   2. categorias
--   3. productos
--   4. domiciliarios
--   5. suscripciones
--   6. pedidos
--
-- Incluye:
--   - Extensión pgcrypto para UUIDs
--   - Restricciones de integridad y claves foráneas en cascada
--   - Índices de alto rendimiento
--   - Políticas de seguridad RLS
--   - Publicación en Realtime para pedidos y productos
--   - Configuración del Bucket de Storage ('product-images')
--   - Trigger de consistencia automática de estados
-- ═══════════════════════════════════════════════════════════════════════════════

-- Habilitar extensión pgcrypto
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. LIMPIEZA PREVIA (Opcional si existen tablas incompletas o corruptas)
-- ─────────────────────────────────────────────────────────────────────────────
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS domiciliarios CASCADE;
DROP TABLE IF EXISTS suscripciones CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;
DROP TABLE IF EXISTS negocios CASCADE;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. CREACIÓN DE TABLAS (DDL)
-- ─────────────────────────────────────────────────────────────────────────────

-- TABLA 1: NEGOCIOS
CREATE TABLE negocios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID, -- ID de usuario registrado en Supabase Auth
  nombre TEXT NOT NULL UNIQUE, -- Slug único en URL (ej: /dogcity, /pizzaliberty)
  nombre_visible TEXT NOT NULL,
  telefono TEXT,
  whatsapp_contacto TEXT,
  direccion TEXT,
  theme_color TEXT DEFAULT '#EA580C',
  color_secundario TEXT DEFAULT '#FFF7ED',
  instagram TEXT,
  facebook TEXT,
  tiktok TEXT,
  footer_message TEXT,
  pago_banco TEXT,
  pago_alias TEXT,
  metodos_pago JSONB DEFAULT '["efectivo","transferencia"]'::jsonb,
  lat NUMERIC,
  lng NUMERIC,
  tipo_domicilio TEXT DEFAULT 'automatico',
  costo_por_km NUMERIC DEFAULT 0,
  domicilio_minimo NUMERIC DEFAULT 0,
  precio_domicilio NUMERIC DEFAULT 0,
  logo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA 2: CATEGORÍAS
CREATE TABLE categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id UUID NOT NULL REFERENCES negocios(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT uq_categorias_negocio_nombre UNIQUE (negocio_id, nombre)
);

-- TABLA 3: PRODUCTOS
CREATE TABLE productos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id UUID NOT NULL REFERENCES negocios(id) ON DELETE CASCADE,
  categoria_id BIGINT REFERENCES categorias(id) ON DELETE SET NULL,
  nombre TEXT NOT NULL,
  precio NUMERIC NOT NULL DEFAULT 0,
  descripcion TEXT DEFAULT '',
  unidad TEXT DEFAULT 'unidad',
  imagen TEXT DEFAULT '',
  categoria TEXT DEFAULT '',
  disponible BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA 4: DOMICILIARIOS / REPARTIDORES
CREATE TABLE domiciliarios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  negocio_id UUID NOT NULL REFERENCES negocios(id) ON DELETE CASCADE,
  nombre TEXT NOT NULL,
  telefono TEXT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- TABLA 5: SUSCRIPCIONES SAAS
CREATE TABLE suscripciones (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  negocio_id UUID NOT NULL REFERENCES negocios(id) ON DELETE CASCADE,
  plan TEXT NOT NULL DEFAULT 'pro',
  estado TEXT NOT NULL DEFAULT 'trial',
  es_trial BOOLEAN NOT NULL DEFAULT true,
  fecha_inicio TIMESTAMPTZ DEFAULT NOW(),
  fecha_fin TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT uq_suscripciones_negocio UNIQUE (negocio_id)
);

-- TABLA 6: PEDIDOS
CREATE TABLE pedidos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id UUID NOT NULL REFERENCES negocios(id) ON DELETE CASCADE,
  domiciliario_id UUID REFERENCES domiciliarios(id) ON DELETE SET NULL,
  nombre TEXT NOT NULL,
  telefono TEXT NOT NULL,
  direccion TEXT,
  ubicacion_link TEXT,
  comentarios TEXT DEFAULT '',
  total NUMERIC NOT NULL DEFAULT 0,
  domicilio_costo NUMERIC DEFAULT 0,
  distancia_km NUMERIC,
  items JSONB DEFAULT '[]'::jsonb,
  productos JSONB DEFAULT '[]'::jsonb,
  estado TEXT DEFAULT 'nuevo',
  status TEXT DEFAULT 'nuevo',
  entrega_metodo TEXT DEFAULT 'envio',
  pago_metodo TEXT DEFAULT 'efectivo',
  token TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. TRIGGER DE SINCRONIZACIÓN AUTOMÁTICA DE ESTADOS EN PEDIDOS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION fn_sync_pedido_status()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    NEW.estado := NEW.status;
  ELSIF NEW.estado IS DISTINCT FROM OLD.estado THEN
    NEW.status := NEW.estado;
  END IF;

  IF NEW.items IS DISTINCT FROM OLD.items AND (NEW.productos IS NULL OR NEW.productos = '[]'::jsonb) THEN
    NEW.productos := NEW.items;
  ELSIF NEW.productos IS DISTINCT FROM OLD.productos AND (NEW.items IS NULL OR NEW.items = '[]'::jsonb) THEN
    NEW.items := NEW.productos;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sync_pedido_status
BEFORE INSERT OR UPDATE ON pedidos
FOR EACH ROW EXECUTE FUNCTION fn_sync_pedido_status();

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. ÍNDICES DE RENDIMIENTO
-- ─────────────────────────────────────────────────────────────────────────────
CREATE INDEX idx_negocios_nombre ON negocios(nombre);
CREATE INDEX idx_negocios_user_id ON negocios(user_id);
CREATE INDEX idx_categorias_negocio ON categorias(negocio_id);
CREATE INDEX idx_productos_negocio ON productos(negocio_id);
CREATE INDEX idx_productos_categoria ON productos(categoria_id);
CREATE INDEX idx_domiciliarios_negocio ON domiciliarios(negocio_id);
CREATE INDEX idx_suscripciones_negocio ON suscripciones(negocio_id);
CREATE INDEX idx_pedidos_negocio ON pedidos(negocio_id);
CREATE INDEX idx_pedidos_token ON pedidos(token);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. POLÍTICAS DE ACCESO (ROW LEVEL SECURITY)
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE negocios ENABLE ROW LEVEL SECURITY;
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE domiciliarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE suscripciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public access on negocios" ON negocios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access on categorias" ON categorias FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access on productos" ON productos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access on domiciliarios" ON domiciliarios FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access on suscripciones" ON suscripciones FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access on pedidos" ON pedidos FOR ALL USING (true) WITH CHECK (true);

-- ─────────────────────────────────────────────────────────────────────────────
-- 6. PUBLICACIÓN REALTIME Y STORAGE BUCKET
-- ─────────────────────────────────────────────────────────────────────────────
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE pedidos;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE productos;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;
END $$;

DO $$
BEGIN
  INSERT INTO storage.buckets (id, name, public)
  VALUES ('product-images', 'product-images', true)
  ON CONFLICT (id) DO UPDATE SET public = true;
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

DO $$
BEGIN
  DROP POLICY IF EXISTS "Public Access product-images" ON storage.objects;
  CREATE POLICY "Public Access product-images" ON storage.objects
    FOR ALL USING (bucket_id = 'product-images')
    WITH CHECK (bucket_id = 'product-images');
EXCEPTION WHEN OTHERS THEN NULL;
END $$;
