-- NEGU: esquema completo de Supabase. Ejecutar este archivo como única instalación.
-- Reejecutable: no elimina tablas ni datos existentes.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.negocios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid,
  nombre text NOT NULL UNIQUE, nombre_visible text NOT NULL,
  telefono text, whatsapp_contacto text, direccion text,
  theme_color text DEFAULT '#EA580C', color_secundario text DEFAULT '#FFF7ED',
  instagram text, facebook text, tiktok text, footer_message text,
  pago_banco text, pago_alias text, metodos_pago jsonb DEFAULT '["efectivo","transferencia"]'::jsonb,
  lat numeric, lng numeric, tipo_domicilio text DEFAULT 'automatico',
  costo_por_km numeric DEFAULT 0, domicilio_minimo numeric DEFAULT 0,
  precio_domicilio numeric DEFAULT 0, logo_url text,
  business_type varchar(50) NOT NULL DEFAULT 'general',
  created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.categorias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id uuid NOT NULL REFERENCES public.negocios(id) ON DELETE CASCADE,
  nombre text NOT NULL, created_at timestamptz DEFAULT now(),
  CONSTRAINT uq_categorias_negocio_nombre UNIQUE (negocio_id,nombre)
);
CREATE TABLE IF NOT EXISTS public.productos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id uuid NOT NULL REFERENCES public.negocios(id) ON DELETE CASCADE,
  categoria_id bigint REFERENCES public.categorias(id) ON DELETE SET NULL,
  nombre text NOT NULL, precio numeric NOT NULL DEFAULT 0, descripcion text DEFAULT '',
  unidad text DEFAULT 'unidad', imagen text DEFAULT '', categoria text DEFAULT '',
  disponible boolean DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.domiciliarios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  negocio_id uuid NOT NULL REFERENCES public.negocios(id) ON DELETE CASCADE,
  nombre text NOT NULL, telefono text NOT NULL, activo boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.suscripciones (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  negocio_id uuid NOT NULL REFERENCES public.negocios(id) ON DELETE CASCADE,
  plan text NOT NULL DEFAULT 'pro', estado text NOT NULL DEFAULT 'trial', es_trial boolean NOT NULL DEFAULT true,
  fecha_inicio timestamptz DEFAULT now(), fecha_fin timestamptz,
  created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(),
  CONSTRAINT uq_suscripciones_negocio UNIQUE (negocio_id)
);
CREATE TABLE IF NOT EXISTS public.pedidos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  negocio_id uuid NOT NULL REFERENCES public.negocios(id) ON DELETE CASCADE,
  domiciliario_id uuid REFERENCES public.domiciliarios(id) ON DELETE SET NULL,
  nombre text NOT NULL, telefono text NOT NULL, direccion text, ubicacion_link text, comentarios text DEFAULT '',
  total numeric NOT NULL DEFAULT 0, domicilio_costo numeric DEFAULT 0, distancia_km numeric,
  items jsonb DEFAULT '[]'::jsonb, productos jsonb DEFAULT '[]'::jsonb,
  estado text DEFAULT 'nuevo', status text DEFAULT 'nuevo', entrega_metodo text DEFAULT 'envio',
  pago_metodo text DEFAULT 'efectivo', token text,
  delivery_type varchar(50) NOT NULL DEFAULT 'fixed', delivery_fee numeric(12,2) NOT NULL DEFAULT 0,
  subtotal_amount numeric(12,2) NOT NULL DEFAULT 0, total_amount numeric(12,2) NOT NULL DEFAULT 0,
  cancellation_reason text, cancelled_by varchar(20), payment_method varchar(50) DEFAULT 'cash',
  payment_receipt_url text, payment_status varchar(30) NOT NULL DEFAULT 'pending',
  quote_sent_at timestamptz, confirmed_at timestamptz,
  created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now()
);

-- Completar instalaciones previas sin borrar datos.
ALTER TABLE public.negocios ADD COLUMN IF NOT EXISTS business_type varchar(50) NOT NULL DEFAULT 'general';
ALTER TABLE public.pedidos
  ADD COLUMN IF NOT EXISTS delivery_type varchar(50) NOT NULL DEFAULT 'fixed',
  ADD COLUMN IF NOT EXISTS delivery_fee numeric(12,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS subtotal_amount numeric(12,2),
  ADD COLUMN IF NOT EXISTS total_amount numeric(12,2),
  ADD COLUMN IF NOT EXISTS cancellation_reason text,
  ADD COLUMN IF NOT EXISTS cancelled_by varchar(20),
  ADD COLUMN IF NOT EXISTS payment_method varchar(50) DEFAULT 'cash',
  ADD COLUMN IF NOT EXISTS payment_receipt_url text,
  ADD COLUMN IF NOT EXISTS payment_status varchar(30) NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS quote_sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS confirmed_at timestamptz;
UPDATE public.pedidos SET delivery_fee=COALESCE(domicilio_costo,0),
  total_amount=COALESCE(total,0), subtotal_amount=GREATEST(COALESCE(total,0)-COALESCE(domicilio_costo,0),0)
WHERE total_amount IS NULL OR subtotal_amount IS NULL;
ALTER TABLE public.pedidos ALTER COLUMN subtotal_amount SET DEFAULT 0, ALTER COLUMN subtotal_amount SET NOT NULL,
  ALTER COLUMN total_amount SET DEFAULT 0, ALTER COLUMN total_amount SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_negocios_nombre ON public.negocios(nombre);
CREATE INDEX IF NOT EXISTS idx_negocios_user_id ON public.negocios(user_id);
CREATE INDEX IF NOT EXISTS idx_categorias_negocio ON public.categorias(negocio_id);
CREATE INDEX IF NOT EXISTS idx_productos_negocio ON public.productos(negocio_id);
CREATE INDEX IF NOT EXISTS idx_productos_categoria ON public.productos(categoria_id);
CREATE INDEX IF NOT EXISTS idx_domiciliarios_negocio ON public.domiciliarios(negocio_id);
CREATE INDEX IF NOT EXISTS idx_suscripciones_negocio ON public.suscripciones(negocio_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_negocio ON public.pedidos(negocio_id);
CREATE INDEX IF NOT EXISTS idx_pedidos_token ON public.pedidos(token);
CREATE INDEX IF NOT EXISTS idx_pedidos_quote_status ON public.pedidos(negocio_id,status,created_at DESC);

CREATE OR REPLACE FUNCTION public.fn_sync_pedido_status() RETURNS trigger
LANGUAGE plpgsql SET search_path=public,pg_temp AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN NEW.estado:=NEW.status;
  ELSIF NEW.estado IS DISTINCT FROM OLD.estado THEN NEW.status:=NEW.estado; END IF;
  IF NEW.items IS DISTINCT FROM OLD.items AND (NEW.productos IS NULL OR NEW.productos='[]'::jsonb) THEN NEW.productos:=NEW.items;
  ELSIF NEW.productos IS DISTINCT FROM OLD.productos AND (NEW.items IS NULL OR NEW.items='[]'::jsonb) THEN NEW.items:=NEW.productos; END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_sync_pedido_status ON public.pedidos;
CREATE TRIGGER trg_sync_pedido_status BEFORE INSERT OR UPDATE ON public.pedidos
FOR EACH ROW EXECUTE FUNCTION public.fn_sync_pedido_status();

CREATE OR REPLACE FUNCTION public.guard_customer_order_cancellation() RETURNS trigger
LANGUAGE plpgsql SET search_path=public,pg_temp AS $$
BEGIN
  IF NEW.cancelled_by='customer' AND NEW.status='CANCELADO' THEN
    IF OLD.status NOT IN ('COTIZACION_ENVIADA','CONFIRMADO_GRACIA') OR OLD.estado NOT IN ('COTIZACION_ENVIADA','CONFIRMADO_GRACIA') THEN
      RAISE EXCEPTION 'El pedido ya no se puede cancelar desde el seguimiento';
    END IF;
    IF OLD.status='CONFIRMADO_GRACIA' AND (OLD.confirmed_at IS NULL OR OLD.confirmed_at < now()-interval '60 seconds') THEN
      RAISE EXCEPTION 'Terminó el tiempo para deshacer el pedido';
    END IF;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_guard_customer_cancel ON public.pedidos;
CREATE TRIGGER trg_guard_customer_cancel BEFORE UPDATE ON public.pedidos
FOR EACH ROW EXECUTE FUNCTION public.guard_customer_order_cancellation();

-- Acceso público de catálogo; escritura de catálogo sólo para el comercio propietario.
ALTER TABLE public.negocios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.productos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domiciliarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.suscripciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public access on negocios" ON public.negocios;
DROP POLICY IF EXISTS "Public access on categorias" ON public.categorias;
DROP POLICY IF EXISTS "Public access on productos" ON public.productos;
DROP POLICY IF EXISTS "Public access on domiciliarios" ON public.domiciliarios;
DROP POLICY IF EXISTS "Public access on suscripciones" ON public.suscripciones;
DROP POLICY IF EXISTS "Public access on pedidos" ON public.pedidos;
DROP POLICY IF EXISTS "Public read pedidos" ON public.pedidos;
DROP POLICY IF EXISTS "negocios_public_read" ON public.negocios;
DROP POLICY IF EXISTS "negocios_owner_write" ON public.negocios;
DROP POLICY IF EXISTS "categorias_public_read" ON public.categorias;
DROP POLICY IF EXISTS "categorias_owner_write" ON public.categorias;
DROP POLICY IF EXISTS "productos_public_read" ON public.productos;
DROP POLICY IF EXISTS "productos_owner_write" ON public.productos;
DROP POLICY IF EXISTS "domiciliarios_owner_all" ON public.domiciliarios;
DROP POLICY IF EXISTS "suscripciones_public_read" ON public.suscripciones;
DROP POLICY IF EXISTS "suscripciones_owner_write" ON public.suscripciones;
DROP POLICY IF EXISTS "Public insert pedidos" ON public.pedidos;
DROP POLICY IF EXISTS "Tenant read pedidos" ON public.pedidos;
DROP POLICY IF EXISTS "Tenant update pedidos" ON public.pedidos;
CREATE POLICY negocios_public_read ON public.negocios FOR SELECT TO anon,authenticated USING (true);
CREATE POLICY negocios_owner_write ON public.negocios FOR ALL TO authenticated USING (user_id=auth.uid()) WITH CHECK (user_id=auth.uid());
CREATE POLICY categorias_public_read ON public.categorias FOR SELECT TO anon,authenticated USING (true);
CREATE POLICY categorias_owner_write ON public.categorias FOR ALL TO authenticated USING (EXISTS(SELECT 1 FROM public.negocios n WHERE n.id=negocio_id AND n.user_id=auth.uid())) WITH CHECK (EXISTS(SELECT 1 FROM public.negocios n WHERE n.id=negocio_id AND n.user_id=auth.uid()));
CREATE POLICY productos_public_read ON public.productos FOR SELECT TO anon,authenticated USING (true);
CREATE POLICY productos_owner_write ON public.productos FOR ALL TO authenticated USING (EXISTS(SELECT 1 FROM public.negocios n WHERE n.id=negocio_id AND n.user_id=auth.uid())) WITH CHECK (EXISTS(SELECT 1 FROM public.negocios n WHERE n.id=negocio_id AND n.user_id=auth.uid()));
CREATE POLICY domiciliarios_owner_all ON public.domiciliarios FOR ALL TO authenticated USING (EXISTS(SELECT 1 FROM public.negocios n WHERE n.id=negocio_id AND n.user_id=auth.uid())) WITH CHECK (EXISTS(SELECT 1 FROM public.negocios n WHERE n.id=negocio_id AND n.user_id=auth.uid()));
CREATE POLICY suscripciones_public_read ON public.suscripciones FOR SELECT TO anon,authenticated USING (true);
CREATE POLICY suscripciones_owner_write ON public.suscripciones FOR ALL TO authenticated USING (EXISTS(SELECT 1 FROM public.negocios n WHERE n.id=negocio_id AND n.user_id=auth.uid())) WITH CHECK (EXISTS(SELECT 1 FROM public.negocios n WHERE n.id=negocio_id AND n.user_id=auth.uid()));
CREATE POLICY "Public insert pedidos" ON public.pedidos FOR INSERT TO anon,authenticated WITH CHECK (true);
CREATE POLICY "Tenant read pedidos" ON public.pedidos FOR SELECT TO authenticated USING (EXISTS(SELECT 1 FROM public.negocios n WHERE n.id=negocio_id AND n.user_id=auth.uid()));
CREATE POLICY "Tenant update pedidos" ON public.pedidos FOR UPDATE TO authenticated USING (EXISTS(SELECT 1 FROM public.negocios n WHERE n.id=negocio_id AND n.user_id=auth.uid())) WITH CHECK (EXISTS(SELECT 1 FROM public.negocios n WHERE n.id=negocio_id AND n.user_id=auth.uid()));

GRANT SELECT ON public.negocios,public.categorias,public.productos,public.suscripciones TO anon,authenticated;
GRANT INSERT,UPDATE,DELETE ON public.negocios,public.categorias,public.productos,public.domiciliarios,public.suscripciones TO authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.pedidos TO authenticated;
GRANT INSERT ON public.pedidos TO anon;
REVOKE UPDATE,DELETE ON public.pedidos FROM anon,PUBLIC;

CREATE OR REPLACE FUNCTION public.customer_get_order(p_order_id bigint,p_token text) RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
  SELECT to_jsonb(p)||jsonb_build_object('negocios',CASE WHEN n.id IS NULL THEN NULL ELSE jsonb_build_object(
    'id',n.id,'nombre',n.nombre,'nombre_visible',n.nombre_visible,'telefono',n.telefono,
    'whatsapp_contacto',n.whatsapp_contacto,'logo_url',n.logo_url,'theme_color',n.theme_color,
    'business_type',n.business_type,'nequi_numero',n.pago_alias,'daviplata_numero',n.pago_alias,
    'titular_cuenta',n.nombre_visible,'pago_banco',n.pago_banco,'pago_alias',n.pago_alias) END)
  FROM public.pedidos p LEFT JOIN public.negocios n ON n.id=p.negocio_id
  WHERE p.id=p_order_id AND p.token=p_token LIMIT 1;
$$;
CREATE OR REPLACE FUNCTION public.customer_accept_quote(p_order_id bigint,p_token text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE o public.pedidos%ROWTYPE;
BEGIN
  SELECT * INTO o FROM public.pedidos WHERE id=p_order_id AND token=p_token FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Pedido o token inválido'; END IF;
  IF o.status<>'COTIZACION_ENVIADA' OR o.estado<>'COTIZACION_ENVIADA' THEN RAISE EXCEPTION 'La cotización ya no está disponible'; END IF;
  UPDATE public.pedidos SET status='CONFIRMADO_GRACIA',estado='CONFIRMADO_GRACIA',confirmed_at=now(),updated_at=now() WHERE id=p_order_id;
  RETURN jsonb_build_object('success',true,'status','CONFIRMADO_GRACIA','confirmed_at',now());
END $$;
CREATE OR REPLACE FUNCTION public.customer_cancel_order(p_order_id bigint,p_token text,p_reason text DEFAULT 'Cancelado por el cliente') RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE o public.pedidos%ROWTYPE;
BEGIN
  SELECT * INTO o FROM public.pedidos WHERE id=p_order_id AND token=p_token FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Pedido o token inválido'; END IF;
  IF o.status NOT IN ('COTIZACION_ENVIADA','CONFIRMADO_GRACIA') OR o.estado NOT IN ('COTIZACION_ENVIADA','CONFIRMADO_GRACIA') THEN RAISE EXCEPTION 'El pedido ya no se puede cancelar desde el seguimiento'; END IF;
  IF o.status='CONFIRMADO_GRACIA' AND (o.confirmed_at IS NULL OR o.confirmed_at<now()-interval '60 seconds') THEN RAISE EXCEPTION 'Terminó el tiempo para deshacer el pedido'; END IF;
  UPDATE public.pedidos SET status='CANCELADO',estado='CANCELADO',cancelled_by='customer',cancellation_reason=left(coalesce(p_reason,'Cancelado por el cliente'),500),updated_at=now() WHERE id=p_order_id;
  RETURN jsonb_build_object('success',true,'status','CANCELADO');
END $$;
CREATE OR REPLACE FUNCTION public.advance_grace_to_kitchen(p_order_id bigint,p_token text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE o public.pedidos%ROWTYPE;
BEGIN
  SELECT * INTO o FROM public.pedidos WHERE id=p_order_id AND token=p_token FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Pedido o token inválido'; END IF;
  IF o.status<>'CONFIRMADO_GRACIA' OR o.estado<>'CONFIRMADO_GRACIA' OR o.confirmed_at IS NULL OR o.confirmed_at>now()-interval '60 seconds' THEN RAISE EXCEPTION 'El período de gracia sigue activo o el pedido cambió'; END IF;
  UPDATE public.pedidos SET status='EN_PREPARACION',estado='EN_PREPARACION',updated_at=now() WHERE id=p_order_id;
  RETURN jsonb_build_object('success',true,'status','EN_PREPARACION');
END $$;
CREATE OR REPLACE FUNCTION public.customer_save_receipt(p_order_id bigint,p_token text,p_storage_path text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
BEGIN
  IF p_storage_path NOT LIKE p_order_id::text||'/'||p_token||'/%' THEN RAISE EXCEPTION 'Ruta de comprobante inválida'; END IF;
  UPDATE public.pedidos SET payment_receipt_url=p_storage_path,payment_status='pending',updated_at=now() WHERE id=p_order_id AND token=p_token;
  IF NOT FOUND THEN RAISE EXCEPTION 'Pedido o token inválido'; END IF;
  RETURN jsonb_build_object('success',true,'path',p_storage_path);
END $$;
CREATE OR REPLACE FUNCTION public.receipt_path_authorized(p_order_id text,p_token text) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
  SELECT EXISTS(SELECT 1 FROM public.pedidos p WHERE p.id::text=p_order_id AND p.token=p_token)
$$;
REVOKE ALL ON FUNCTION public.customer_get_order(bigint,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.customer_accept_quote(bigint,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.customer_cancel_order(bigint,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.advance_grace_to_kitchen(bigint,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.customer_save_receipt(bigint,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.receipt_path_authorized(text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.customer_get_order(bigint,text),public.customer_accept_quote(bigint,text),public.advance_grace_to_kitchen(bigint,text),public.customer_save_receipt(bigint,text,text),public.receipt_path_authorized(text,text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.customer_cancel_order(bigint,text,text) TO anon,authenticated;

-- Supabase Storage: imágenes públicas del catálogo y comprobantes privados ligados a pedido+token.
INSERT INTO storage.buckets(id,name,public) VALUES('product-images','product-images',true)
ON CONFLICT(id) DO UPDATE SET public=true;
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
VALUES('receipts','receipts',false,10485760,ARRAY['image/jpeg','image/png','image/webp','application/pdf'])
ON CONFLICT(id) DO UPDATE SET public=false,file_size_limit=10485760,allowed_mime_types=ARRAY['image/jpeg','image/png','image/webp','application/pdf'];
DROP POLICY IF EXISTS "Public Access product-images" ON storage.objects;
CREATE POLICY "Public Access product-images" ON storage.objects FOR ALL USING(bucket_id='product-images') WITH CHECK(bucket_id='product-images');
DROP POLICY IF EXISTS "Public Receipt Upload" ON storage.objects;
DROP POLICY IF EXISTS "Public Receipt Read" ON storage.objects;
DROP POLICY IF EXISTS "Token Receipt Upload" ON storage.objects;
DROP POLICY IF EXISTS "Token Receipt Read" ON storage.objects;
CREATE POLICY "Token Receipt Upload" ON storage.objects FOR INSERT TO anon,authenticated
WITH CHECK(bucket_id='receipts' AND public.receipt_path_authorized((storage.foldername(name))[1],(storage.foldername(name))[2]));
CREATE POLICY "Token Receipt Read" ON storage.objects FOR SELECT TO anon,authenticated
USING(bucket_id='receipts' AND public.receipt_path_authorized((storage.foldername(name))[1],(storage.foldername(name))[2]));

DO $$ BEGIN
  IF EXISTS(SELECT 1 FROM pg_publication WHERE pubname='supabase_realtime') THEN
    IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='pedidos') THEN ALTER PUBLICATION supabase_realtime ADD TABLE public.pedidos; END IF;
    IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='productos') THEN ALTER PUBLICATION supabase_realtime ADD TABLE public.productos; END IF;
  END IF;
END $$;
NOTIFY pgrst,'reload schema';
